# Generated by Django 6.0.4 on 2026-04-16 22:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=50, verbose_name='Familiya')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Otasining ismi')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail manzil')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Telefon raqam')),
                ('role', models.CharField(choices=[('teacher', 'Ustoz'), ('admin', 'Admin'), ('superuser', 'Superadmin')], verbose_name='Xodim lavozimi')),
                ('is_superuser', models.BooleanField(default=False, help_text='Eng yuqori darajadagi huquq, bunday turdagi xodim uchun hech qanday taqiq mavjud emas', verbose_name='Superadminlik statusi')),
                ('is_staff', models.BooleanField(default=False, help_text='Xodim admin panelga kira olishi yoki kira olmasligini bildiradi', verbose_name='Xodimlik statusi')),
                ('is_active', models.BooleanField(default=True, help_text="Xodim akkauntini o'chirib yuborish o'rniga shunchaki shu sohani o'chiring", verbose_name='Akkaunt aktivlik statusi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['-created'],
                'unique_together': {('first_name', 'last_name', 'middle_name')},
            },
        ),
    ]
