# Generated by Django 6.0.4 on 2026-04-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expensecategory_alter_user_role_class_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='born_year',
            field=models.DateField(blank=True, null=True, verbose_name='Год рождения'),
        ),
    ]
