# Generated by Django 6.0.4 on 2026-04-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_born_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='born_year',
            new_name='birthday',
        ),
    ]
