# Generated by Django 6.0.4 on 2026-04-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_class_students_student_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=20, verbose_name='Месяц, для которого заносится оплата'),
        ),
    ]
